[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
  "probe-rs",
  "run",
  "--chip",
  "STM32G031K8",
  "--log-format",
  "{t:blue} {L} {s} {f:magenta}:{l:magenta}",
]

# https://defmt.ferrous-systems.com/custom-log-output

[build]
# target = "thumbv7em-none-eabi"
target = "thumbv6m-none-eabi"

# trace, debug, info, warn, error
[env]
DEFMT_LOG = "info"